export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  llmProviderPrimary: process.env.LLM_PROVIDER_PRIMARY ?? "gemini",
  llmProviderFallback1: process.env.LLM_PROVIDER_FALLBACK_1 ?? "forge",
  llmProviderFallback2: process.env.LLM_PROVIDER_FALLBACK_2 ?? "none",
  llmModelPrimary: process.env.LLM_MODEL_PRIMARY ?? "gemini-1.5-flash",
  llmModelFallback1: process.env.LLM_MODEL_FALLBACK_1 ?? "gpt-4o-mini",
  llmModelFallback2: process.env.LLM_MODEL_FALLBACK_2 ?? "",
  geminiApiKey: process.env.GEMINI_API_KEY ?? "",
  openRouterApiKey: process.env.OPENROUTER_API_KEY ?? "",
  openRouterApiUrl: process.env.OPENROUTER_API_URL ?? "https://openrouter.ai/api/v1/chat/completions",
  groqApiKey: process.env.GROQ_API_KEY ?? "",
  groqApiUrl: process.env.GROQ_API_URL ?? "https://api.groq.com/openai/v1/chat/completions",
  llmFailoverTimeoutMs: Number(process.env.LLM_FAILOVER_TIMEOUT_MS ?? 8000),
};
